### PR TITLE
Implement Ord and PartialOrd for Symbol

### PR DESCRIPTION
**Pull request by michaelmior**
This just allows comparison of symbols.
Needed this because my use involves sorting a vector.

### CODE REVIEW

**Comment by tailhook** [comment]
Sounds good. Thank you!

**Comment by michaelmior** [comment]
Thanks for the quick merge!

**Comment by michaelmior** [comment]
Also, any idea when you might release a new version?

**Comment by tailhook** [comment]
> Also, any idea when you might release a new version?

v0.1.6 is already at crates.io when you were writing the text :)

**Comment by michaelmior** [comment]
:heart:

**Pull request merged**
